services:
    routmoute-steam-bundle.apiservice:
        class: Routmoute\Bundle\RoutmouteSteamBundle\Service\RoutmouteSteamApiService
        autowire: true
        arguments:
            $steam_apikey: '%routmoute_steam.steam_apikey%'

    Routmoute\Bundle\RoutmouteSteamBundle\Service\RoutmouteSteamApiService:
        alias: routmoute-steam-bundle.apiservice
